# Generated by Django 2.0.3 on 2019-02-04 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='collaborate',
        ),
        migrations.AddField(
            model_name='notes',
            name='collaborate',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
