# Generated by Django 2.0.3 on 2019-02-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190204_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=150)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Notes')),
            ],
        ),
    ]
