# Generated by Django 2.0.3 on 2019-02-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Notes'),
        ),
    ]
