# Generated by Django 2.0.3 on 2019-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190206_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='note_id',
            field=models.IntegerField(default=None),
        ),
    ]
