# Generated by Django 2.0.3 on 2019-02-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190206_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='note_id',
        ),
    ]
