# Generated by Django 2.0.3 on 2019-02-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190207_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='note_id',
        ),
        migrations.AddField(
            model_name='labels',
            name='note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Notes'),
        ),
    ]
